### ISSUE TITLE
Subfolders inside stylesheets folder

### ISSUE THREAD

**Issue by chanpory** [lucasefe/themes_for_rails#10]
Looks like themes_for_rails doesn't support subfolders within the stylesheets folder. I have a stylesheet which references an `images` folder inside the `stylesheets` folder. However, the stylesheet can't find the image file I'm trying to reference. When I visit the URL for the image like:

`http://my.site.com/themes/my_theme/stylesheets/images/my_image.png`

I get the following error:

`not found`

**Comment by lucasefe** [comment]
I'll check on this, and the remaining tickets, on Monday. I am really busy right now, but I expect to get some spare time on next week. 

Sorry for the delay, for the waiting... 

Lucas
