### ISSUE TITLE
Passing options to asset inclusion methods

### ISSUE THREAD

**Issue by matheusmoreira** [lucasefe/themes_for_rails#12]
To allow for maximum flexibility, it would be nice if we could specify options to the asset inclusion tags which would then be forwarded to Rails' methods, so that the following, for example, is possible:

```
theme_stylesheet_link_tag "blueprint/screen", :media => "screen, projection"
theme_stylesheet_link_tag "blueprint/print", :media => "print"
```

Here's a possible implementation:

```
def theme_stylesheet_link_tag(file, *opts)
  stylesheet_link_tag theme_stylesheet_path(file), *opts
end
```

The ideal would be to able to use your methods transparently, as if we were using Rails' methods:

```
theme_stylesheet_link_tag :all, :recursive => true
theme_javascript_include_tag :defaults
```

**Comment by lucasefe** [comment]
Fixed! :)
