### ISSUE TITLE
Subfolders inside stylesheets folder

### ISSUE THREAD

**Issue by chanpory** [lucasefe/themes_for_rails#14]
(Accidentally closed this issue, reopening)

Looks like themes_for_rails doesn't support subfolders within the stylesheets folder. I have a stylesheet which references an `images` folder inside the `stylesheets` folder. However, the stylesheet can't find the image file I'm trying to reference. When I visit the URL for the image like:

`http://my.site.com/themes/my_theme/stylesheets/images/my_image.png`

I get the following error:

`not found`

**Comment by lucasefe** [comment]
chanpory, I have pushed a new version solving that problem. Would you be so kind to try it out a little bit? Use it with bundler like this:

gem 'themes_for_rails', :git => 'git://github.com/lucasefe/themes_for_rails.git'

Let me know how it works, please. 

Thanks

**Comment by chanpory** [comment]
Yes it works now! Thank you!
