### ISSUE TITLE
generator missing

### ISSUE THREAD

**Issue by wdbmh** [lucasefe/themes_for_rails#16]
After executing: "rails generate themes_for_rails:install" I get the message "Could not find generator themes_for_rails:install"

**Comment by lucasefe** [comment]
Would you like to provide me more context? Did add the gem to your gem file and run bundle install?
Rails version?

**Comment by wdbmh** [comment]
Rails 3. I followed the instruction. Added gem to gemfile. Did bundle install. I can use everything, only the generators are not working
