### ISSUE TITLE
Incompatible with Heroku

### ISSUE THREAD

**Issue by dmathieu** [lucasefe/themes_for_rails#2]
Hello,

I've not tested more than that to see the reasons. But this gem isn't compatible with heroku.
The static files are just not displayed.

**Comment by lucasefe** [comment]
I have not use it on heroku. I understand that the filesystem is readonly, right? 

By the way, have you disabled the x-sendfile support on your production.rb file? I had that problem in the beginning. This should only be enabled if you have x-sendfile enabled on your web server.

**Comment by lucasefe** [comment]
Any new comments regarding this issue?
