### ISSUE TITLE
config base_dir + generate themes_for_rails:theme

### ISSUE THREAD

**Issue by chrisbraddock** [lucasefe/themes_for_rails#21]
Should lib/generators/themes_for_rails/theme_generator.rb use config.themes_for_rails.base_dir instead of File.join(Rails.root, "themes") for themes_path or am I misunderstanding things?

**Comment by lucasefe** [comment]
You are right! I've fixed it. Tell me what do you think (it's on master).

Cheers

**Comment by chrisbraddock** [comment]
Looks good!  I have this in an initializer: config.themes_dir = 'app/themes' and now the generator "themes" seems to do what I'd expect.  Thanks!
