### ISSUE TITLE
Themes urls do not have rails_asset_id appended to them

### ISSUE THREAD

**Issue by scottillogical** [lucasefe/themes_for_rails#24]

**Comment by scottillogical** [comment]
okay so it's because rails appends the asset_id generated  by checking the timestamp on the asset in the assets_dir, which defaults to public/ but now for these specific stylesheets should be /theme...

**Comment by lucasefe** [comment]
Scott, maybe I am missing something (probably) but I don't understand what seems to be the problem. Displayed assets that are inside /themes don not include the "?5454647" thing at the end?

**Comment by scottillogical** [comment]
so rails has this thing where it appends a unique id that respresents when the files is changed to prevent browser caching when you update a css file.

because the theming plugin serves stylesheets from /theme/ and rails doesn't know about it, this know longer works.

the side effect is that when you deploy and update to a theme css file most browsers will cache it and your site will break

**Comment by lucasefe** [comment]
GIve me few days and I'll fix this. Thanks for reporting it.

**Comment by scottillogical** [comment]
it's not blocking me so no rush, i could also fix it but haven't gotten around to it

**Comment by scottillogical** [comment]
https://github.com/rails/rails/blob/70dba7414b60a21797b7862b0edf89d2630e1897/actionpack/lib/action_view/helpers/asset_tag_helper.rb#L746

Here is basically where it happens...config.asset_path is set to /public, and it assumes that when it checks the timestamp of themed assets.   

I'm actually not sure how to fix this.  If image_tag allowed us to pass a absolute path in,  instead of relying on that config var, that would fix it...but it doesn't.   We could also duplicate the asset id generation ourselves.

**Comment by scottillogical** [comment]
of course, in HEAD they've changed to location of that code to be here

https://github.com/rails/rails/blob/1c129f8f8ea5b10605ad77af6064c983584d463d/actionpack/lib/action_view/helpers/asset_tag_helpers/asset_id_caching.rb

**Comment by lucasefe** [comment]
Long time passed after this... Closing it.
