### ISSUE TITLE
Themes stored in Database

### ISSUE THREAD

**Issue by shenoudab** [lucasefe/themes_for_rails#26]
Dears, 

 i was looking for storing these themes in Database, as every user have and create his own theme. and to be also available of editing by users.

how that can be done with themes_for_rails

Best Regards,
Shenouda Bertel

**Comment by mgladkov** [comment]
I think you should create some uploading mechanism first.
After that, you will place each theme in separate folder and put link to this folder into database.
Then you should load theme for each user separately from his folder.

**Comment by lucasefe** [comment]
Let me see if I get it. Do you want to store css, js and images files on the database? Or only the theme names? 

First option seems kind of difficult. Also, probably this is not something that ThemesForRails should do. may be I am wrong, so feel free to expand on the subject. 

Thanks.
