### ISSUE TITLE
Theme Names with Characters

### ISSUE THREAD

**Issue by deep-spaced** [lucasefe/themes_for_rails#27]
I've got a theme with a period in the name such as testing.site. Unfortunately when I use the link tag helper:

```
<%= theme_stylesheet_link_tag 'styles' %>
```

It throws the following error:

```
No route matches {:controller=>"themes_for_rails/assets", :theme=>"testing.site", :asset=>"styles.css", :action=>"stylesheets"}
```

Any ideas?

**Comment by lucasefe** [comment]
Hi, better later than never. Fixed on master. This will be released soon as a new gem. 

Thanks for the report.
