### ISSUE TITLE
Conflict with Rails Footnotes

### ISSUE THREAD

**Issue by rrouse** [lucasefe/themes_for_rails#31]
This may be more of an FYI, but when Rails Footnotes is turned on, the theme specific static files (stylesheets, javascripts) are returned as blank files. When you turn Rails Footnotes off, the static assets start working.

**Comment by lucasefe** [comment]
This is clearly old... :S Sorry for the delay. 

I am closing this, and if you think this still happening, please, provide some more information regarding it. 

Thanks
