### ISSUE TITLE
cache the *.css and *.js files

### ISSUE THREAD

**Issue by roverway** [lucasefe/themes_for_rails#32]
i found that when i use a customized theme, every time i refresh the page, all of the js and css files will be download, i thought this is a waste of resource, and can you do some fixes on your gem to add a cache function also make this gem more perfect??

**Comment by Olli** [comment]
just take a look at

```
rake themes:create_cache           # Creates the cached theme folder
rake themes:remove_cache           # Removes the cached (public) theme folders
rake themes:update_cache           # Updates the cached (public) theme folders
```

I used the cached view for development because the usual way ( files in themes/ ) is too slow.

**Comment by roverway** [comment]
o, i'm so careless. now, it's a perfect gem for me.
