### ISSUE TITLE
seeding data from a specific theme

### ISSUE THREAD

**Issue by joaomilho** [lucasefe/themes_for_rails#35]
Hi guys, I guess somthing like that would be useful...

namespace :db do
  namespace :seed do
    desc "Seeds a theme Usage: rake db:seed:theme THEME=your_theme"
    task :theme => :environment do |t, args|
      load(File.join(Rails.root, 'themes', ENV["THEME"], 'db', 'seed.rb'))
    end
  end
end

**Comment by lucasefe** [comment]
Joao, hi!

I think this piece of code doesn't belong to this plugin. A theme only represent a part of the view that is changeable, but your rake task deals with data (model).

**Comment by joaomilho** [comment]
Yeah, I understand. But in my case a theme is a cliente, so I need to seed some example data that fits the client... I don't know if more people use it like that.
