### ISSUE TITLE
Problem with rspec view tests

### ISSUE THREAD

**Issue by m3nd3s** [lucasefe/themes_for_rails#36]
I'm using Rspec to test my application, but after I added the themes_for_rails and move my html.erb files to themes/my_theme/views folder my view tests dosn't works.

The Rspec show me missing template error. There is a way to solve this problem? Or I'm doing something wrong?

Thanks

**Comment by lucasefe** [comment]
Are you setting up the theme at controller level to 'my_theme'? If no theme is specified, then the view will not be visible. 

Please, provide some code example. 

Thanks
