### ISSUE TITLE
Rails dependency added twice

### ISSUE THREAD

**Issue by kenips** [lucasefe/themes_for_rails#38]
Hey Lucus,

In https://github.com/lucasefe/themes_for_rails/commit/e172443bb071917d1d6ac2c7cc6ee4cff0c3a2ce, you added rails dependency twice, so it actually depends on Rails 3.0 now, not Rails 3.1.

Cheers,
Ken

**Comment by lucasefe** [comment]
You are right! Im on it.

**Comment by lucasefe** [comment]
gem "themes_for_rails", "1.0.0rc1". Fixed :)
