### ISSUE TITLE
Question about theme support at css(sass)

### ISSUE THREAD

**Issue by arufanov** [lucasefe/themes_for_rails#41]
Hi!

-1.This is not problem, just question. I have not found more suitable place to put my questions.
-2.There are theme_image_tag & image_tag to overload an image at theme, but there are also css (sass) with code like this:
"
      li
        list-style: none
        background: url(/images/decorators/square.png) left 2px no-repeat

"

Is any way to select rigth image at css/sass based on current theme? Are you planning to do something to resolve this problem? If yes, what exactly (I will try to help)? 

Artem.

**Comment by lucasefe** [comment]
To do that, you will have to use the asset pipeline, on rails 3.1 or later, and mixed ruby variables on the sass templates. 

Unfortunately, ThemesForRails doesn't work with the new Assets Pipeline. I am still thinking about how to integrate it properly. I did some tests, but I did not like the solution. 

If you want, please elaborate a little bit more.

**Comment by arufanov** [comment]
Hello, 

Thank you for answer, I will take a look at asset pipeline and understand is it suitable for my requirements or not. 

Sincerely yours,
Artem Rufanov

P.S.
Have a good day!
