### ISSUE TITLE
Theme support for yml files

### ISSUE THREAD

**Issue by arufanov** [lucasefe/themes_for_rails#42]
Hi!

-1.This is not problem, just question. I have not found more suitable place to put my questions.
-2.There are yml files for trunslation and I am using it like this:
<li><%= link_to t("sitemap.mapitems.primary.common.about_us"), {:controller => '/welcome', :action => "about_us"}%></li>
Are you planning to provide a overloading text for theme?  If yes, what exactly (I will try to help)?

Artem.

**Comment by lucasefe** [comment]
I really haven't thought about it... If you want, please elaborate about this issue, so I know what are thinking. I may be a god idea. 

Thanks

**Comment by arufanov** [comment]
Hi!

-1.Sorry for delay.  Internet wasn’t available for me.
-2.Lets we have partition  _logo.html.erb:

<div id="logo">
  <%= link_to(image_tag("logos/mylogo.png", {:alt =>t("mylogo"), :title => t("mylogo")}), :controller => "/welcome") %>
</div>

and I would like to add a theme support. Currently I must create themes/theme1/views/_logo.html.erb like this: 

<div id="logo">
  <%= link_to(theme_image_tag("logos/mylogo.png", {:alt =>t("mylogo1"), :title => t("mylogo1")}), :controller => "/welcome") %>
</div>

This will give a new mylogo.png and new alt and title. If you add a new helper theme_t that gives text from theme local file then I may have only one partition like this:

<div id="logo">
  <%= link_to(theme_image_tag("logos/mylogo.png", {:alt =>theme_t("mylogo "), :title => theme_t("my mylogo ")}), :controller => "/welcome") %>
</div>


This is quite simple example,  that demonstrates what I need.  But ideas behind is clear: you should allow supporting any content for theme including images and text resources. If you need more information let me know.

Sincerely yours,
Artem Rufanov.

P.S.
Have a goo day!
