### ISSUE TITLE
theme_stylesheet_path for files with extension differs from standard rails 

### ISSUE THREAD

**Issue by edrex** [lucasefe/themes_for_rails#45]
Where Rails' stylesheet_path will let you add your own extension, theme_stylesheet_path still tacks on the default extension, which is a problem for using it with for example LESS.js:

``` erb
= stylesheet_path 'FOO.less'
= theme_stylesheet_path 'BAR.less'
```

```
/stylesheets/FOO.less
/themes/activate/stylesheets/BAR.less.css
```

**Comment by lucasefe** [comment]
Please, let me know if this issue still happens on the current version of  themes_for_rails.
