### ISSUE TITLE
bundle show an error with the gemspec file 

### ISSUE THREAD

**Issue by GARUMFundatio** [lucasefe/themes_for_rails#49]
bundle show themes_for_rails
Invalid gemspec in [/opt/bazarfactory/Bazar/vendor/ruby/1.8/specifications/themes_for_rails-0.5.0.gemspec]: Illformed requirement ["#YAML::Syck::DefaultKey:0x8ae0c10 3.0.11"]
Could not find themes_for_rails-0.5.0 in any of the sources

**Comment by lucasefe** [comment]
@GARUMFundatio Could you please indicate your rails and ruby version? Thanks

**Comment by GARUMFundatio** [comment]
ruby 1.8.7 (2011-02-18 patchlevel 334) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2011.03
rails (3.0.7)
Bundler version 1.0.15

**Comment by lucasefe** [comment]
Hey, @GARUMFundatio, I don't have a ruby 1.8.7. Also, this issue has been already reported here [1]. See my response there. Sorry for the inconvenience. 

[1] - https://github.com/lucasefe/themes_for_rails/issues/47

**Comment by GARUMFundatio** [comment]
Okey, I will try to workaround the problem.

It's so weird and for now I cann't migrate all my server to 1.9 ;-(

Thanks again for the support and the gem ;-)

Juantomás García
608 189 047 - 606 505 322

On Wed, Apr 18, 2012 at 18:57, Lucas Florio <
reply@reply.github.com
