### ISSUE TITLE
conflict setting theme and layout

### ISSUE THREAD

**Issue by shenoudab** [lucasefe/themes_for_rails#5]
Dears, 

  i'm using theme for rails in my Rails3 Application with Devise.
 the problem is that devise can set custom layouts as follow :

layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "layout_name_for_devise"
    else
      "application"
    end
  end

what if i'd like to set a theme in any of these conditions as follow :

layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "layout_name_for_devise"
    else
     theme "application"
    end
  end

how this can be done please advise

**Comment by lucasefe** [comment]
I don't get it. 

themes_for_rails offers alternative paths to views, so you could have a theme named "red" that contains a layout named "application", and a theme named "blue" which also have a layout named "application". Both layout files are named the same. 

What I think you need to do is something like this: 

<pre>
def layout_by_resource
  if devise_controller?
    # Provided that you have theme for each Devise role.     
    theme resource_name # admin, or user, or whatever. 
  else
    theme 'public' # I am just saying... as an example
  end
  return "application"
end
</pre>

Does it make any sense?

**Comment by shenoudab** [comment]
Ya, that what i'm asking for.

but : layout_by_resource may return Theme or a layout from default application layouts.

because if i add this line to application_controller "layout :layout_by_resource" then ":layout_by_resource" must return "layout" and not a theme.

**Comment by lucasefe** [comment]
In the solution I have provided we are returning always a layout name. You always return "application" as layout name. What is changing on each request is the theme_name, but the layout name is always the same one. 

May I am missing something, shenaudab. Would you like to provide a GIST with more context information?

**Comment by shenoudab** [comment]
kindly, find the provided gist http://gist.github.com/662570

**Comment by lucasefe** [comment]
On line 8, 10, 14 and 17 you return a String (probably a layout name), on 12 you return a theme, and in line 20 you set the layout explicitly. 
In theory, a method should only return one kind of response. 

I think you should probably got to have another method for setting the theme name.

But to be honest, I think there is a problem in your design. What are you trying to accomplish with this method? Can you try to explain me that. Sometimes, explaining helps to see the problems.

**Comment by shenoudab** [comment]
kindly, what is being done is :

   not in all conditions i will set a theme, but only in one or 2 cases only.
 the rest of conditions should set layout "form default layouts", and the theme should set a theme "as default of themes_for_rails".

the code in the gist will return error, as the method should only return one kind of response.

how can i set a layout or a theme according to the current condition ?

please, send any questions for clarification or information.

**Comment by lucasefe** [comment]
Clearly, at least not refactoring the method that much, you should always, always, always, return a string, that being the layout name. If you also need to change the theme, you should change it in the previous line. You never need to return the theme name. 

I really don't know what "form default layouts" and "as default of themes_for_rails" means. Could you clarify? 

Thanks

**Comment by shenoudab** [comment]
Thanks for your help :

"From default layout" => "layout from /app/views/layouts/..."
"Default of themes" => "theme from /themes/...."

then i have to create to methods one for selecting layouts and other for selecting themes.

what if i didn't like to select theme in one of the conditions.

is there any way to combine the two methods in one method for both "layouts and themes"

**Comment by lucasefe** [comment]
You know that we are not talking about themes_for_rails or devise anymore, right? This is about your application's implementation. 

If you don't want to select a theme, then just leave it. It will not add the theme's view path, so this behavior will be just like any standard rails app.

**Comment by shenoudab** [comment]
Thanks for support.
