### ISSUE TITLE
URL helpers error - Asset Pipeline

### ISSUE THREAD

**Issue by danbronsema** [lucasefe/themes_for_rails#50]
When trying to use the URL helpers:
current_theme_image_path('logo.png', 'theme_name')   # => /themes/theme_name/images/logo.png

I get the following error:
undefined method `base_theme_javascript_path' for #Frontend::ItemsController:0x007ffa85926aa8

I'm using the Split Theme Storage method, and have included the relevant initializers. Do I need to include a 'default' theme for the url helpers to work?

I'm not sure where base_theme... exists in the source, and couldn't find much documentation about it. I'd be glad for some heads up, I'm going to contribute some more documentation once I figure it all out. It's a very handy gem!

**Comment by danbronsema** [comment]
I totally missed this step:
- add the “themes_for_rails” route in the routes.rb

Still don't know where the base_theme... method is called from however.
I'm thinking of adding some documentation to make this a little clearer.

**Comment by lucasefe** [comment]
@galaxylord So it's working? Great to hear that.
