### ISSUE TITLE
Sass compilation stopped working

### ISSUE THREAD

**Issue by rvrm** [lucasefe/themes_for_rails#61]
The theme's stylesheet dir has the regular "sass" sub directory, yet the .sass file therein is not compiled to css. The sass gem is installed. What might be missing?

**Comment by lucasefe** [comment]
Did you upgraded an existing app? Or was it a new one? Are you using the Assets pipeline?

If you are using tfr with the assets pipeline, you should have your css files named file.css.sass in order to get file.css, alright? 

I need more information in order to give you any useful hand.

**Comment by rvrm** [comment]
Pinned down the error to this line in my _application.rb_:
`require 'bootstrap-sass'`
This prevents my theme's Sass-file from being compiled.

**Comment by lucasefe** [comment]
Do it like this:

```
@import "bootstrap-sass"
```

Maybe this works better. In any case, this is not related to themes_for_rails, IMO.
