### ISSUE TITLE
Liquid Support for Themes

### ISSUE THREAD

**Issue by shenoudab** [lucasefe/themes_for_rails#7]
Dears, 

 kindly, i was asking about supporting Liquid Templating in Themes_for_rails.
and how to handle liquid templates inside themes.

and also supporting other templating like Mustache and handlebars in themes.

**Comment by lucasefe** [comment]
As far as I know, if you make liquid work in your Rails app, it will work with no modification with themes_for_rails. Any template language that works with rails, works with ThemesForRails.

**Comment by lucasefe** [comment]
Closing... If in doubt, please, create a new one.
